name: keyboard_safe
description: >
  A lightweight Flutter widget that prevents keyboard overflow by automatically adjusting layout, scrolling input fields into view, and providing sticky footers above the keyboard.
version: 1.0.0
repository: https://github.com/ChathraNavoda/keyboard_safe
homepage: https://github.com/ChathraNavoda/keyboard_safe
issue_tracker: https://github.com/ChathraNavoda/keyboard_safe/issues

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - keyboard
  - layout
  - textfields
  - overflow
  - focus

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:
